### Register API
POST http://localhost:3000/register HTTP/1.1
content-type: application/json

{
	"userName": "aleem",
	"email": "aleemaheerup@gmail.com",
	"password": "12345678!",
	"confirm_password": "12345678!"
}

### Change password API
PUT http://localhost:3000/account/1
content-type: application/json

{
	"oldPassword": "12345678!",
	"newPassword": "hello####",
	"confirmPassword": "hello####"
}

### Forget password API 1
POST http://localhost:3000/forgot
content-type: application/json

{
	"userName": "aleem",
	"email": "aleemaheerup@gmail.com"
}

### Forget password API 2
PUT http://localhost:3000/forgot
content-type: application/json

{
	"email": "aleemaheerup@gmail.com",
	"token": "9e82jd844n99e82jd844n9",
	"password": "hello@@@@",
	"confirmPassword": "hello@@@@"
}
### Login
POST http://localhost:3000/login HTTP/1.1
content-type: application/json

{
	"email": "aleemaheerup@gmail.com",
	"password": "12345678!"
}

### POST REQUEST TO CREATE TODO
POST http://localhost:3000/todos HTTP/1.1
content-type: application/json
user_id: 1

{
	"title": "Wash clothes",
	"description": "This is todos"
}

### GET All TODOS
GET http://localhost:3000/todos HTTP/1.1
user_id: 1

### GET SINGLE TODO
GET http://localhost:3000/todos/2 HTTP/1.1
user_id: 12

### PATCH REQUEST TO UPDATE STATUS OF TODO
PATCH http://localhost:3000/todos/1 HTTP/1.1
content-type: application/json
user_id: 1

{
	"isCompleted" : true
}

### DELETE REQUEST
DELETE http://localhost:3000/todos/2 HTTP/1.1
user_id: 1

### PUT REQUEST TO UPDATE TODO
PUT http://localhost:3000/todos/1 HTTP/1.1
content-type: application/json
user_id: 1

{
	"title": "Clean clothes",
	"description": "Clean all the dishes before the guests came",
	"isCompleted": true
}