### Register API
POST http://localhost:3000/register HTTP/1.1
content-type: application/json

{
	"userName": "ali",
	"email": "ali@todos.com"
}

### Login
POST http://localhost:3000/login HTTP/1.1
content-type: application/json

{
	"email": "ali@todos.com"
}

### Post request for user to post his todos
POST http://localhost:3000/todos/create HTTP/1.1
content-type: application/json
user_id: 1

{
	"title": "Wash clothes 2",
	"description": "This is aleem's todos"
}

### GET All TODOS
GET http://localhost:3000/todos HTTP/1.1
user_id: 18

### GET SINGLE TODO
GET http://localhost:3000/todos/1 HTTP/1.1
user_id: 2

### UPDATE STATUS OF TODO
PUT http://localhost:3000/todos/updateStatus/5 HTTP/1.1
content-type: application/json
user_id: 1

{
	"isCompleted": true
}

### DELETE REQUEST
DELETE http://localhost:3000/todos/1 HTTP/1.1
user_id: 1

### PUT REQUEST
PUT http://localhost:3000/todos/3 HTTP/1.1
content-type: application/json
user-id: 1

{
	"title": "Clean dishes",
	"description": "Clean all the dishes before the guests came",
	"isCompleted": true
}