### Register API
POST http://localhost:3000/register HTTP/1.1
content-type: application/json

{
	"userName": "aleem",
	"email": "aleemaheer1238@gmail.com",
	"password": "12345678!",
	"confirm_password": "12345678!"
}

### Change password API
PUT http://localhost:3000/account/2
content-type: application/json

{
	"oldPassword": "12345678!",
	"newPassword": "hello####",
	"confirmPassword": "hello####"
}

### Forget password API 1
POST http://localhost:3000/forgot
content-type: application/json

{
	"userName": "aleem",
	"email": "aleemaheer5769644@gmail.com"
}

### Forget password API 2
PUT http://localhost:3000/forgot
content-type: application/json

{
	"email": "aleemaheer5769644@gmail.com",
	"token": "4p3vuv06i5p4p3vuv06i5p",
	"password": "hello@@@@",
	"confirmPassword": "hello@@@@"
}
### Login
POST http://localhost:3000/login HTTP/1.1
content-type: application/json

{
	"email": "aleemaheer1238@gmail.com",
	"password": "12345678!"
}

### POST REQUEST TO CREATE TODO
POST http://localhost:3000/todos HTTP/1.1
content-type: application/json
user_id: 16

{
	"title": "I am good",
	"description": "This todo is for testing purpose"
}

### GET All TODOS
GET http://localhost:3000/todos HTTP/1.1
user_id: 16

### GET SINGLE TODO
GET http://localhost:3000/todos/50 HTTP/1.1
user_id: 16

### PATCH REQUEST TO UPDATE STATUS OF TODO
PATCH http://localhost:3000/todos/2 HTTP/1.1
content-type: application/json
user_id: 1

{
	"isCompleted" : true
}

### DELETE REQUEST
DELETE http://localhost:3000/todos/2 HTTP/1.1
user_id: 1

### PUT REQUEST TO UPDATE TODO
PUT http://localhost:3000/todos/1 HTTP/1.1
content-type: application/json
user_id: 1

{
	"title": "Clean clothes",
	"description": "Clean all the dishes before the guests came",
	"isCompleted": true
}